### ISSUE TITLE
Complex font types PDF is not being converted

### ISSUE THREAD

**Issue by cryptooman** [coolwanglu/pdf2htmlEX#460]
When converting PDF TypesettingSample.pdf the result is blank page.
The PDF can be taken from here: ... unavailable ...

-- Regards, Dmitry

**Comment by coolwanglu** [comment]
I can no longer access the URL. Can you upload it again?

**Comment by cryptooman** [comment]
URL no longer available. Please get PDF from https://www.dropbox.com/s/v0lr1u9vsplagme/TypesettingSample.pdf?dl=0

**Comment by coolwanglu** [comment]
I tested with you PDF file.

The first pages uses CID Type0 OpenType fonts, which was not supported by pdf2htmlEX before. And I've just fixed in the `incoming` branch.

For the rest 2 pages, unfortunately seems that the font files used cannot be supported by poppler. You may not be able to view the files correctly with a PDF viewer using poppler. You may report a bug to poppler if you like :)

Thanks for reporting, can I use the PDF file as a test case for pdf2htmlEX?

**Comment by coolwanglu** [comment]
Remarks on poppler, there's a warning `Syntax Warning: Mismatch between font type and embedded font file`, so it could be something wrong in the PDF file instead.

**Comment by cryptooman** [comment]
Thanks for quick reply. I've got it. Yes, of course you can use PDF.

**Comment by coolwanglu** [comment]
Thanks!

**Comment by WAKSAB** [comment]
Poker

**Comment by cryptooman** [comment]
Found one more issue with converted results markup: https://gretawolf.ru/upload/iblock/198/CATALOGUE%20CAROCIM%20L%20-%202018-19%20(2).pdf
![markup-errors](https://user-images.githubusercontent.com/5260290/41649566-8ee0e694-7484-11e8-8dce-978f92e1344a.png)
Attached the screenshot.
