### ISSUE TITLE
Feature Request: Work with Linux Piping and Redirection

### ISSUE THREAD

**Issue by prmph** [coolwanglu/pdf2htmlEX#638]
Can we have the program to accept the input file as piped output from another program or from STDIN as a byte stream?

Also, can the program be made to support piping the output (the actual HTML output, not the messages) to other programs or to STDOUT ?

These enhancements will greatly increase the usefulness of pdf2htmlEX.

**Comment by duanyao** [comment]
A PDF file can't be read sequentially, and the output of pdf2htmlEX is not always a single file.

**Comment by prmph** [comment]
The PDF file input stream can be buffered until completely received, before it is converted. Also, we can pipe out only the first file output, because in many cases you are just outputting a single file.

**Comment by duanyao** [comment]
Buffering the entire PDF consumes more memory than necessary. What problem are you trying to solve?

**Comment by prmph** [comment]
But when you execute the pdf2htmlEX command the PDF is loaded into memory anyway? 

I am writing an Express.js server, and I want to start streaming the output as soon as it is available, instead of waiting to write to a file before sending to the client. Also don't want to be creating physical files all over the place when the request come in.

**Comment by duanyao** [comment]
No, pdf2htmlEX loads and processes one page of PDF one time, so the memory reqiurement for processing PDF is constant, not proportional to page numbers.

How do you generate your PDF files? PDF format is not designed for streaming, so you have to wait until a entire PDF is generated to start pdf -> html conversion.

For output streaming, I think you may use [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) to avoid creating physical files and use node.js [`fs.watch()`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) to monitor the output file. I think you want the output to be a file rather than a stream, because the network connection may break in the middle and users want to retry in this case.

However, currently pdf2htmlEX is not quite suitable for streaming-while-converting, because the html and css are generated after all pages of PDF are processed, and changing this is non-trivial (but possible).

**Comment by prmph** [comment]
Ok, thanks for the explanation.
